<?php

namespace tests;

use App\User;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{
    public $user;

    public function test_retrieve_name()
    {
        $this->assertEquals("Samy", $this->user->name());
    }

    public function test_retrieve_email()
    {
        $this->assertEquals("Samy@gmail.com", $this->user->email());
    }

    public function test_set_name()
    {
        $this->user->name("hassan");
        $this->assertEquals("hassan", $this->user->name());
    }

    public function test_set_email()
    {
        $this->user->email("hassan@gmail.com");
        $this->assertEquals("hassan@gmail.com", $this->user->email());
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User("Samy", "Samy@gmail.com");
    }


}